# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real Estate Watch - Blog
email: ziggy@elephant-bird.net
description: > # this means to ignore newlines until "baseurl:"
  Real Estate Watch is a community project keeping our eyes on developers, the city, and the powers that profit and promote gentrification in New York City.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

pages:
  - research
  - wiki
  - blog

